### ISSUE TITLE
Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1

### ISSUE THREAD

**Issue by JSBmanD** [GoogleCloudPlatform/recaptcha-enterprise-flutter#31]
I'm having a problem on the latest flutter (3.19.0). Can't build an app.

<details>
  <summary>The error</summary>

```
/Projects/rhino/cc/.dart_tool/flutter_build/1168011eba0ac20d05a2346c37b118ec/kernel_snapshot.d
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.common_common_ktx.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.common_logger.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.enterprise.android_impl.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.enterprise.internal.release.com.google.android.recaptcha.internal_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.enterprise.internal_impl.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.enterprise.internal_internal.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.enterprise.native_impl.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.enterprise.public_public.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.enterprise_enterprise.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.metricscollection_metricscollection.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.network_network.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/recaptcha.proto.mobile_allowlist_kt_proto_lite.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/recaptcha.proto.mobile_enterprise_sdk_kt_proto_lite.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/recaptcha.proto.mobile_mobile_reload_kt_proto_lite.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/recaptcha.proto.mobile_webview_sdk_kt_proto_lite.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/third_party.java_src.protobuf.current.java.com.google.protobuf.kotlin_only_for_use_in_proto_generated_code_its_generator_and_tests.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/third_party.java_src.protobuf.current.java.com.google.protobuf.kotlin_shared_runtime.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (21, 37): Class 'com.google.android.recaptcha.Recaptcha' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/Recaptcha.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (22, 37): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (23, 37): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (37, 41): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (47, 37): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (48, 12): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (49, 36): Class 'com.google.android.recaptcha.RecaptchaAction.Companion' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction$Companion.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (49, 36): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (49, 52): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (50, 37): Class 'com.google.android.recaptcha.RecaptchaAction.Companion' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction$Companion.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (50, 37): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (50, 53): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (51, 15): Class 'com.google.android.recaptcha.RecaptchaAction.Companion' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction$Companion.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (51, 15): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (51, 31): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (66, 34): Class 'com.google.android.recaptcha.Recaptcha' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/Recaptcha.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (67, 18): Class 'com.google.android.recaptcha.Recaptcha' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/Recaptcha.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (70, 13): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (70, 31): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (79, 16): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (79, 49): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (90, 18): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (93, 7): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (94, 10): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (94, 37): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (94, 40): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (94, 48): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (94, 79): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (94, 82): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.1/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (94, 90): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/790b5c8e7573db5eeb661606857e8f86/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':recaptcha_enterprise_flutter:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s

┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                     │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then │
│ update /Users/dmitry/Documents/Projects/rhino/cc/android/build.gradle:                     │
│ ext.kotlin_version = '<latest-version>'                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────┘
Error: Gradle task assembleDebug failed with exit code 1
```

<details>
  <summary>build.gradle</summary>

```
buildscript {
    ext.kotlin_version = '1.9.21'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        // START: FlutterFire Configuration
        classpath 'com.google.gms:google-services:4.3.14'
        // END: FlutterFire Configuration
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```
</details>

**Comment by walterjgsp** [comment]
Thanks for the report @JSBmanD. The new SDK 18.4.1 and 18.4.2 need Kotlin 1.9.0 version on Android. We just released the new version updating that. What's the version of Kotlin that you're using in your Android app `build.gradle`?

**Comment by walterjgsp** [comment]
Does this issue also occurs with the new version that was released? Did you try to clean the Gradle cache?

**Comment by mcorner** [comment]
As we.have not heard back we will close this issue.

**Comment by JSBmanD** [comment]
I finally managed to upgrade and I still get this error. These are all my dependencies versions:
recaptcha_enterprise_flutter: 18.4.2
distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.1-all.zip
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.1'
    ext.kotlin_version = '1.9.23'

<details>
  <summary>Error</summary>
  

```
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.common_common_ktx.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.common_logger.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.enterprise.android_impl.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.enterprise.internal.release.com.google.android.recaptcha.internal_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.enterprise.internal_impl.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.enterprise.internal_internal.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.enterprise.native_impl.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.enterprise.public_public.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.enterprise_enterprise.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.metricscollection_metricscollection.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/java.com.google.android.libraries.abuse.recaptcha.network_network.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/recaptcha.proto.mobile_allowlist_kt_proto_lite.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/recaptcha.proto.mobile_enterprise_sdk_kt_proto_lite.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/recaptcha.proto.mobile_mobile_reload_kt_proto_lite.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/recaptcha.proto.mobile_webview_sdk_kt_proto_lite.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/third_party.java_src.protobuf.current.java.com.google.protobuf.kotlin_only_for_use_in_proto_generated_code_its_generator_and_tests.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/META-INF/third_party.java_src.protobuf.current.java.com.google.protobuf.kotlin_shared_runtime.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (21, 37): Class 'com.google.android.recaptcha.Recaptcha' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/Recaptcha.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (22, 37): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (23, 37): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (37, 41): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (47, 37): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (48, 12): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (49, 36): Class 'com.google.android.recaptcha.RecaptchaAction.Companion' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction$Companion.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (49, 36): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (49, 52): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (50, 37): Class 'com.google.android.recaptcha.RecaptchaAction.Companion' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction$Companion.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (50, 37): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (50, 53): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (51, 15): Class 'com.google.android.recaptcha.RecaptchaAction.Companion' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction$Companion.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (51, 15): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (51, 31): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (66, 34): Class 'com.google.android.recaptcha.Recaptcha' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/Recaptcha.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (67, 18): Class 'com.google.android.recaptcha.Recaptcha' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/Recaptcha.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (70, 13): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (70, 31): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (79, 16): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (79, 49): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (90, 18): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (93, 7): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (94, 10): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (94, 37): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (94, 40): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (94, 48): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (94, 79): Class 'com.google.android.recaptcha.RecaptchaClient' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaClient.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (94, 82): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class
e: /Users/dmitry/.pub-cache/hosted/pub.dev/recaptcha_enterprise_flutter-18.4.2/android/src/main/kotlin/com/google/flutter/recaptcha/RecaptchaEnterprisePlugin.kt: (94, 90): Class 'com.google.android.recaptcha.RecaptchaAction' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from /Users/dmitry/.gradle/caches/transforms-3/f8c9f9ecd37edce2a07ee6f23cefe5a0/transformed/jetified-recaptcha-18.4.0-api.jar!/com/google/android/recaptcha/RecaptchaAction.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':recaptcha_enterprise_flutter:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```
</details>

**Comment by JSBmanD** [comment]
I've added this `freeCompilerArgs += ["-Xskip-metadata-version-check"]` to kotlinOptions to android/build.gradle of the package and now it's working. Not sure if it's ok to have this in package but it will fix the issue.

**Comment by mcorner** [comment]
Somehow you are still compiling with Kotlin 1.7.1.  I don't know why, probably the version is specified somewhere instead of using the variable. We do not suggest ignoring this error I don't know what will happen.

**Comment by fsayfitdinov** [comment]
adding `freeCompilerArgs += ["-Xskip-metadata-version-check"]` did not help me. Is there any other solution to this?
